1. Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array.
Expected Output:
Original List: [12.23, 13.32, 100, 36.32]
One-dimensional NumPy array: [ 12.23 13.32 100. 36.32]


In [5]:
import numpy as np
print("One-dimensional NumPy array: ")
data=np.array([[12.23, 13.32, 100, 36.32]])
print(data)

One-dimensional NumPy array: 
[[ 12.23  13.32 100.    36.32]]


2.	Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.
Expected Output:
[[ 2 3 4]
[ 5 6 7]
[ 8 9 10]]


In [ ]:
data=np.arange(2,11)
a=data.reshape(3,3)
print("Output" , a)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


3.	Write a  NumPy program to create a null vector of size 10 and update the sixth value to 11.
[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value to 11
[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]


In [12]:
df=np.zeros(10)
df[6]=11
print(df)

[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


4.	Write a NumPy program to create an array with values ranging from 12 to 38.
Expected Output:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]


In [14]:
data=np.arange(12,38)
print("Our Output" ,data)

Our Output [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


5.	Write a NumPy program to reverse an array (the first element becomes the last).
Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]


In [16]:
data=np.arange(12,38)
print("Original Array: " ,data)
a=data[::-1]
print("Reversed Array" ,a)

Original Array:  [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reversed Array [37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


6.	Write a  NumPy program to convert an array to a floating type.
Sample output:
Original array
[1, 2, 3, 4]
Array converted to a float type:
[ 1. 2. 3. 4.]


In [ ]:
df=np.array([1,2,3,4],dtype=float)
print("Array Converted to a float type : ",df)


Original Array:  [1. 2. 3. 4.]


7.	Write a NumPy program to create a 2D array with 1 on the border and 0 inside.
Expected Output:
Original array:
[[ 1. 1. 1. 1. 1.]
...................
[ 1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[ 1. 1. 1. 1. 1.]
...................
[ 1. 1. 1. 1. 1.]]


In [24]:
df=np.ones((5,5))
print("Original array: ")
print(df)
df[1:-1,1:-1]=0
print("1 on the border and 0 inside the array ")
print(df)

Original array: 
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside the array 
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


8.	Write a NumPy program to add a border (filled with 0's) around an existing array.
Expected Output:
Original array:
[[ 1. 1. 1.]
[ 1. 1. 1.]
[ 1. 1. 1.]]
1 on the border and 0 inside in the array
[[ 0. 0. 0. 0. 0.]
...........
[ 0. 0. 0. 0. 0.]]


In [25]:
df=np.ones((3,3))
print("Original array : ")
print(df)
a=np.pad(df,pad_width=1,mode='constant',constant_values=0)
print("1 on the border and 0 inside in the array ")
print(a)

Original array : 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
1 on the border and 0 inside in the array 
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


9.	Write a  NumPy program to create an 8x8 matrix and fill it with a checkerboard pattern.
Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
..........
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]]


In [27]:
df=np.zeros((8,8),dtype=int)
df[1::2,::2]=1
df[::2,1::2]=1
print("Checkerboard pattern:")
print(df)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


10.	Write a NumPy program to convert a list and tuple into arrays.
List to array:
[1 2 3 4 5 6 7 8]
Tuple to array:
[[8 4 6]
[1 2 3]]


In [31]:
l=[1,2,3,4,5,6,7,8]
arr=np.array([l])
print("List to array" ,l)
t=((8,4,6),(1,2,3))
trr=np.array(t)
print("Tuple to array : ")
print(trr)


List to array [1, 2, 3, 4, 5, 6, 7, 8]
Tuple to array : 
[[8 4 6]
 [1 2 3]]
